image: gradle:6.4.0-jdk11
stages:
  - build
  - test  
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

buildClient:
  stage: build
  script:
      - |
          echo "Start the build of Client"
          cd Clientgdx
          gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

buildServer:
    stage: build
    script:
        - |
            echo "Start the build of Server"
            cd h2-crud-json
            gradle --build-cache assemble
    artifacts:
      paths:
        - build/libs/*.jar
      expire_in: 1 week
testServer:
  stage: test
  script:
    - |
      echo "Start the test of Server"
      cd h2-crud-json
      gradle --build-cache check
